### ISSUE TITLE
No accounting for 'deleted user' in the metadata post

### ISSUE THREAD

**Issue by superplane39** [izwick-schachter/ips-comment-bot#1]
You can see this [here](https://chat.stackexchange.com/transcript/message/42401140#42401140) - the metadata post has `edited 122 days ago by []() ( rep)` because the [last revision](https://interpersonal.stackexchange.com/posts/4269/revisions) was by a now-deleted user. Minor issue, but still worth saying 'by a deleted user' or somesuch, such as Smokey does?

**Comment by izwick-schachter** [comment]
It should now output `(deleted user <user id>)`
