### ISSUE TITLE
Link to users should just be /u/###, not /u/###/name

### ISSUE THREAD

**Issue by superplane39** [izwick-schachter/ips-comment-bot#2]
Currently, Smelly posts links to users in the format `https://interpersonal.stackexchange.com/u/31/arwen-und%c3%b3miel`. However, this doesn't work - this link format doesn't work. It should just be `https://interpersonal.stackexchange.com/u/31`, as SE doesn't support `/u/<id>/<name>` format links.

**Comment by izwick-schachter** [comment]
Typo in commit message, meant to close #1
